//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAL_JEFES
    {
        public int EMPLEADO { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> TARIFA_POR_HORA { get; set; }
        public Nullable<int> JEFE { get; set; }
    }
}
