//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClientes()
        {
            this.tblNivelesEstudios = new HashSet<tblNivelesEstudios>();
            this.tblPedidosCliente = new HashSet<tblPedidosCliente>();
            this.tblUsuariosIngresosEgresos = new HashSet<tblUsuariosIngresosEgresos>();
        }
    
        public int clienteID { get; set; }
        public int generoID { get; set; }
        public string cedulaCliente { get; set; }
        public string nombresCliente { get; set; }
        public string apellidosCliente { get; set; }
        public string nicknameCliente { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        public virtual tblGeneros tblGeneros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNivelesEstudios> tblNivelesEstudios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPedidosCliente> tblPedidosCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsuariosIngresosEgresos> tblUsuariosIngresosEgresos { get; set; }
    }
}
