//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProductos()
        {
            this.tblPedidosCliente = new HashSet<tblPedidosCliente>();
        }
    
        public int productoID { get; set; }
        public int categoriaID { get; set; }
        public string nomProducto { get; set; }
        public decimal costoProducto { get; set; }
        public int stockProducto { get; set; }
    
        public virtual tblCategoriasProductos tblCategoriasProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPedidosCliente> tblPedidosCliente { get; set; }
    }
}
