//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRegistrosFinancieros
    {
        public int clienteID { get; set; }
        public string cedulaCliente { get; set; }
        public string nombresCliente { get; set; }
        public string apellidosCliente { get; set; }
        public decimal montoIngresoEgreso { get; set; }
        public System.DateTime fechaIngresoEgreso { get; set; }
        public int conceptoID { get; set; }
        public string descTipoConcepto { get; set; }
        public int tipoRegistroID { get; set; }
        public string descripTipoRegistro { get; set; }
    }
}
